name: Publish NuGet

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore DotNetSseClient.slnx

      - name: Build
        run: dotnet build DotNetSseClient.slnx -c Release --no-restore

      - name: Test
        run: dotnet test DotNetSseClient.slnx -c Release --no-build

      - name: Pack
        run: dotnet pack DotNetSseClient/DotNetSseClient.csproj -c Release --no-build -o artifacts/nuget

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
          
      - name: Push package to NuGet
        run: dotnet nuget push "artifacts/nuget/*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
